Tools: Add symbol converter
faebryk/faebryk pull request #112
Opened 2022-07-22 16:20 UTC by IoannisP-ITENG

# Tools: Add symbol converter

# Description
Adds a kicad symbol library to faebryk component library converter.

# Checklist

Please read and execute the following:

- [x] My code follows the [coding guidelines](/faebryk/faebryk/blob/main/docs/CODING_GUIDELINES.md) of this project
- [x] My PR title is following the [contribution guidelines](/faebryk/faebryk/blob/main/docs/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I ran [Black](../docs/CONTRIBUTING.md#creating-a-pull-request) to format my code

#### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](/faebryk/faebryk/blob/main/docs/CODE_OF_CONDUCT.md):

- [x] I agree to follow this project's [Code of Conduct](/faebryk/faebryk/blob/main/docs/CODE_OF_CONDUCT.md)

2022-07-22 16:42 UTC, IoannisP-ITENG commented on tools/symbol_converter/main.py
> +    filepath = "/usr/share/kicad/symbols/Device.kicad_sym"
remove this

2022-07-22 17:00 UTC, ruben-iteng requested changes

2022-07-22 17:00 UTC, ruben-iteng commented on requirements.txt
> +sexpdata
Missing newline at end of file

2022-07-22 17:00 UTC, ruben-iteng commented on tools/symbol_converter/README.md
> +## Usage
Add newline after chapter title

2022-07-22 17:00 UTC, ruben-iteng commented on tools/symbol_converter/README.md
> +```
` ```bash`

2022-07-22 17:00 UTC, ruben-iteng commented on tools/symbol_converter/README.md
> +```
Missing newline at end of file

2022-07-22 17:00 UTC, ruben-iteng commented on tools/symbol_converter/main.py
> +logger.info("hi")
hi

2022-07-22 17:00 UTC, ruben-iteng commented on tools/symbol_converter/main.py
> +    filepath = "/usr/share/kicad/symbols/Device.kicad_sym"
fixed path

2022-07-22 18:00 UTC, ruben-iteng approved these changes
Best faebryk tool there is!

2022-07-29 09:19 UTC, ruben-iteng requested changes

2022-07-29 09:19 UTC, ruben-iteng commented on tools/symbol_converter/main.py
> +        self._setup_traits()
`self._setup_traits()` should be moved to under `self._setup_interfaces()` (line 170)

2022-10-07 13:07 UTC, IoannisP-ITENG commented
superseded

2022-10-07 13:07 UTC, closed without merging